bibliotecario/api/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'api'

urlpatterns = [
    path('', login_required(views.index), name="inicio"),
    path('acessar/', views.loginView, name='acessar'),
    path('sair/', login_required(views.logoutView), name='sair'),

    path('cadastrar/estudante/', login_required(views.cadastrarEstudante), name="cadastrarEstudante"),
    path('pesquisar/estudante/', login_required(views.pesquisarEstudante), name="pesquisarEstudante"),
    path('remover/estudante/', login_required(views.removerEstudante), name="removerEstudante"),

    path('emprestar/livro/', login_required(views.emprestarLivro), name="emprestarLivro"),
    path('emprestandoLivro', login_required(views.emprestandoLivro), name="emprestandoLivro"),
    path('emprestar/livro/realizar/', login_required(views.finalizarEmprestimo), name="emprestandoLivroFinalizar"),
    path('cadastrar/livro/', login_required(views.cadastrarLivro), name="cadastrarLivro"),
    path('receber/livro/', login_required(views.receberLivro), name="receberLivro"),
    path('remover/livro/', login_required(views.removerLivro), name="removerLivro"),
    path('removendoLivro/', login_required(views.removendoLivro), name="removendoLivro"),
    path('listarHistorico', login_required(views.listarHistorico), name="listarHistorico"),
    path('confirmandoEntregaEmprestimo/', login_required(views.confirmandoEntregaEmprestimo), name='confirmandoEntrega'),

]

bibliotecario/bibliotecario/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('api.urls', namespace='api')),
]

bibliotecario/api/models.py
from django.db import models

# Create your models here.

class recuperarSenha(models.Model):
    token = models.CharField(max_length=256)
    emailUser = models.CharField(max_length=40)

bibliotecario/api/forms.py
from django import forms
from django.db import models

class FormularioLogin(forms.Form):
    username = forms.CharField(required=True, label='',
                               widget=forms.TextInput(attrs={'placeholder': 'Usuário', 'class': 'form-control'}))
    password = forms.CharField(required=True, label='',
                               widget=forms.PasswordInput(attrs={'placeholder': 'Senha', 'class': 'form-control'}))

bibliotecario/api/views.py
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.contrib.auth.views import login, logout
from django.http import JsonResponse
import requests, json

IP_estudante = 'http://nginx/estudante'
IP_livro = 'http://nginx/livro'

# Create your views here.
def index(request):
    return render(request, 'index.html')

def loginView(request, *args, **kwargs):

    if request.user.is_authenticated:
        return redirect('api:inicio')

    kwargs['extra_context'] = {'next': reverse('api:acessar')}
    kwargs['template_name'] = 'login.html'
    return login(request, *args, **kwargs)

def logoutView(request, *args, **kwargs):
    kwargs['next_page'] = reverse('api:acessar')
    return logout(request, *args, **kwargs)

'''
    Estudantes
'''

def cadastrarEstudante(request):
    if request.GET is not None:
        return render(request, 'estudante/cadastrar.html')

def pesquisarEstudante(request):
    if request.method == 'GET':
        return render(request, 'estudante/pesquisar.html')
    elif request.method == 'POST':
        matricula = request.POST['matricula']
        session = requests.Session()
        session.trust_env = False
        lista = requests.post(IP_estudante+'/api/buscarEstudante/', data={'matricula': matricula})
        if lista.json()['dados'] != -1:
            template = render_to_string('estudante/listar/pesquisa.html', {'estudantes': lista.json()['dados']})
            return JsonResponse({'retorno': template})
        else:
            return JsonResponse({'retorno': 'Não foi possível encontrar'})

def removerEstudante(request):
    if request.method == 'POST':
        matricula = request.POST['matricula']
        lista = requests.post(IP_estudante + '/api/removerEstudante/', data={'matricula': matricula})
        if lista.json()['deletado']:
            return JsonResponse({'status':'success', 'mensagem':'Estudante removido com sucesso'})
        else:
            return JsonResponse({'status': 'danger', 'mensagem': 'Erro ao remover estudante'})

'''
    Livros
'''

def emprestarLivro(request):
    if request.method == 'GET':
        return render(request, 'livros/emprestar.html')
    elif request.method == 'POST':
        codigo = request.POST['codigo']
        lista = requests.post(IP_livro + '/api/buscarLivroNome/', data={'codigo': codigo})
        if lista.json()['dados'] != -1:
            template = render_to_string('livros/listar/pesquisaEmprestar.html', {'livros': lista.json()['dados']})
            return JsonResponse({'retorno': template})
        else:
            return JsonResponse({'retorno': 'Não foi possível encontrar'})

def emprestandoLivro(request):
    if request.method == 'POST':
        codigo = request.POST['codigo']
        return JsonResponse({'retorno': render_to_string('livros/emprestando.html', {'codigo': codigo})})

def finalizarEmprestimo(request):
    if request.method == 'POST':
        codigo = request.POST['codigo']
        matricula = request.POST['matriculaT']
        if matricula != "":
            verificarEstudante = requests.post(IP_estudante + '/api/verificaEstudante/', data={'matricula': matricula})
            if verificarEstudante.json()['status'] == 1:
                lista = requests.post(IP_livro + '/api/emprestarLivro/', data={'codigo': codigo, 'matricula': matricula})
                if lista.json()['status'] == 1:
                    return JsonResponse({'status': 'success', 'mensagem': 'Livro emprestado com sucesso!'})
            else:
                return JsonResponse({'status': 'danger', 'mensagem': 'Estudante Não Existe'})
        else:
            return JsonResponse({'status': 'danger', 'mensagem': 'Preencha todos os campos!'})


def receberLivro(request):
    if request.method == 'GET':
        return render(request, 'livros/receber.html')
    elif request.method == 'POST':
        matricula = request.POST['matricula']
        lista = requests.post(IP_estudante + '/api/buscarEstudante/', data={'matricula': matricula})
        if lista.json()['dados'] != -1:
            template = render_to_string('livros/listar/estudante.html', {'estudantes': lista.json()['dados']})
            return JsonResponse({'retorno': template})
        else:
            return JsonResponse({'retorno': 'Não foi possível encontrar'})

def cadastrarLivro(request):
    return render(request, 'livros/cadastrar.html')

def removerLivro(request):
    if request.method == 'GET':
        return render(request, 'livros/remover.html')
    elif request.method == 'POST':
        codigo = request.POST['codigo']
        lista = requests.post(IP_livro + '/api/buscarLivro/', data={'codigo': codigo})
        if lista.json()['dados'] != -1:
            template = render_to_string('livros/listar/pesquisa.html', {'livros': lista.json()['dados']})
            return JsonResponse({'retorno': template})
        else:
            return JsonResponse({'retorno': 'Não foi possível encontrar'})

def removendoLivro(request):
    if request.method == 'POST':
        codigo = request.POST['codigo']
        lista = requests.post(IP_livro + '/api/removerLivro/', data={'codigo': codigo})
        if lista.json()['deletado']:
            return JsonResponse({'status':'success', 'mensagem':'Livro removido com sucesso'})
        else:
            return JsonResponse({'status': 'danger', 'mensagem': 'Erro ao remover livro'})

def listarHistorico(request):
    if request.method == 'POST':
        matricula = request.POST['matricula']
        Estudante = requests.post(IP_estudante+'/api/buscarEstudante/', data={'matricula': matricula})
        dados = Estudante.json()['dados'][0]
        nomeEstudante = dados['first_name'] + ' ' + dados['last_name']
        historico = requests.post(IP_livro + '/api/historicoEmprestimos/', data={'matricula': matricula})
        if historico.json()['status'] == 1:
            templateHistorico = render_to_string('livros/listar/alugados.html', {'livros': historico.json()['conteudo']})
            return JsonResponse({'nomeEstudante': nomeEstudante, 'conteudo': templateHistorico})
        else:
            return JsonResponse({'nomeEstudante': nomeEstudante, 'conteudo': "Não há nada nos registros"})

def confirmandoEntregaEmprestimo(request):
    if request.method == 'POST':
        idEmprestimo = request.POST['idEmprestimo']
        confirmando = requests.post(IP_livro + '/api/confirmandoRecebimentoEmprestimo/', data={'idEmprestimo': idEmprestimo})
        print(confirmando)
        if confirmando.json()['status'] == 1:
            return JsonResponse({'status': 'success', 'mensagem': 'Confirmação realizada com sucesso!'})
        else:
            return JsonResponse({'status': 'danger', 'mensagem': 'Erro na confirmação da entrega, tente novamente!'})

bibliotecario/api/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8" />
        <title>Bibliotecário - {% block titulo %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta content="Admin Dashboard" name="description" />
        <meta content="ThemeDesign" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/icons.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">

    </head>


    <body class="fixed-left layout2">

        <!-- Begin page -->
        <div id="wrapper">

            <!-- Top Bar Start -->
            <div class="topbar">
                <!-- LOGO -->
                <div class="topbar-left">
                    <div class="text-center">
                        <a href="{% url 'api:inicio' %}" class="logo">Bibliotecário <span>UFPI</span></a>
                        <a href="{% url 'api:inicio' %}" class="logo-sm"><span>B</span></a>
                        <!--<a href="index.html" class="logo"><img src="{% static 'images/logo_white_2.png" height="28"></a>-->
                        <!--<a href="index.html" class="logo-sm"><img src="{% static 'images/logo_sm.png" height="36"></a>-->
                    </div>
                </div>
                <!-- Button mobile view to collapse sidebar menu -->
                <div class="navbar navbar-default" role="navigation">
                    <div class="container">
                        <div class="">
                            <div class="pull-left">
                                <button type="button" class="button-menu-mobile open-left waves-effect waves-light">
                                    <i class="ion-navicon"></i>
                                </button>
                                <span class="clearfix"></span>
                            </div>

                            <ul class="nav navbar-nav navbar-right pull-right">
                                <li class="dropdown">
                                    <a href="" class="dropdown-toggle profile waves-effect waves-light" data-toggle="dropdown" aria-expanded="true">
                                                <span class="profile-username">
                                                    {{request.user.first_name}} {{request.user.last_name}}<br/>
                                                    <small>Bibliotecário</small>
                                                </span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="{% url 'api:sair' %}"> Sair</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <!--/.nav-collapse -->
                    </div>
                </div>
            </div>
            <!-- Top Bar End -->


            <!-- ========== Left Sidebar Start ========== -->

            <div class="left side-menu">
                <div class="sidebar-inner slimscrollleft">

                    <div class="user-details">
                        <div class="user-info">
                            <div class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">{{request.user.first_name}} {{request.user.last_name}}</a>
                            </div>

                            <p class="text-muted m-0">Bibliotecário</p>
                        </div>
                    </div>
                    <!--- Divider -->


                    <div id="sidebar-menu">
                        <ul>
                            <li>
                                <a href="{% url 'api:inicio' %}" class="waves-effect"><i class="mdi mdi-home"></i><span> Painel Inicial</span></a>
                            </li>

                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect"><i class="fa fa-book"></i> <span> Livros </span> <span class="pull-right"><i class="mdi mdi-plus"></i></span></a>
                                <ul class="list-unstyled">
                                    <li><a href="{% url 'api:emprestarLivro' %}">Emprestar</a></li>
                                    <li><a href="{% url 'api:receberLivro' %}">Receber</a></li>
                                    <li><a href="{% url 'api:cadastrarLivro' %}">Cadastro</a></li>
                                    <li><a href="{% url 'api:removerLivro' %}">Remover</a></li>
                                </ul>
                            </li>

                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-account-multiple"></i> <span> Estudantes </span> <span class="pull-right"><i class="mdi mdi-plus"></i></span></a>
                                <ul class="list-unstyled">
                                    <li><a href="{% url 'api:pesquisarEstudante' %}">Pesquisar</a></li>
                                    <li><a href="{% url 'api:cadastrarEstudante' %}">Cadastrar</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div> <!-- end sidebarinner -->
            </div>
            <!-- Left Sidebar End -->

            <!-- Start right Content here -->

            <div class="content-page">
                <!-- Start content -->
                <div class="content">

                    {% block content %}{% endblock %}

                </div> <!-- content -->

                <footer class="footer">
                    © 2019 UFPI - Todos os direitos reservados.
                </footer>

            </div>
            <!-- End Right content here -->

        </div>
        <!-- END wrapper -->


        <!-- jQuery  -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/modernizr.min.js' %}"></script>
        <script src="{% static 'js/detect.js' %}"></script>
        <script src="{% static 'js/fastclick.js' %}"></script>
        <script src="{% static 'js/jquery.slimscroll.js' %}"></script>
        <script src="{% static 'js/jquery.blockUI.js' %}"></script>
        <script src="{% static 'js/waves.js' %}"></script>
        <script src="{% static 'js/wow.min.js' %}"></script>
        <script src="{% static 'js/jquery.nicescroll.js' %}"></script>
        <script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>

        <script src="{% static 'js/app.js' %}"></script>

        <script src="{% static 'js/formulariosBibliotecario.js' %}"></script>

    </body>
</html>

bibliotecario/api/templates/index.html
{% extends "base.html" %}
{% block titulo %}Início{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-4">
        <div class="panel">
            <div class="panel-body text-center">
                <h2>Livros</h2>
            </div>
        </div>
        <div class="list-group">
            <a href="{% url 'api:emprestarLivro' %}" class="list-group-item">Emprestar</a>
            <a href="{% url 'api:receberLivro' %}" class="list-group-item">Receber</a>
            <a href="{% url 'api:cadastrarLivro' %}" class="list-group-item">Cadastrar</a>
            <a href="{% url 'api:removerLivro' %}" class="list-group-item">Remover</a>
        </div> <!-- list-group -->
    </div>
    <div class="col-md-4">
        <div class="panel">
            <div class="panel-body text-center">
                <h2>Estudantes</h2>
            </div>
        </div>
        <div class="list-group">
            <a href="{% url 'api:pesquisarEstudante' %}" class="list-group-item">Pesquisar</a>
            <a href="{% url 'api:cadastrarEstudante' %}" class="list-group-item">Cadastrar</a>
        </div> <!-- list-group -->
    </div>
    <div class="col-md-2">
    </div>
</div>
{% endblock %}

bibliotecario/api/templates/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8" />
        <title>Bibliotecário - Login</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta content="Admin Dashboard" name="description" />
        <meta content="ThemeDesign" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />


        <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static '/css/icons.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static '/css/style.css' %}" rel="stylesheet" type="text/css">

    </head>


    <body>

        <!-- Begin page -->
        <div class="accountbg"><div class="accountbgOverlay"></div></div>
        <div class="wrapper-page">
            <div class="panel panel-color panel-primary panel-pages">

                <div class="panel-body painelConta">
                    <h3 class="text-center m-t-0 m-b-15">
                        <a href="#" class=" logo-admin"><span>Bibliotecário</span></a>
                        <small><span class="label label-default">UFPI</span></small>
                    </h3>
                    <hr>
                    <h4 class="text-muted text-center m-t-0"><b>Acesso</b></h4>

                    <form class="form-horizontal m-t-20" method="POST">
                        {% csrf_token %}
                        {% if form.errors %}
                            <p class="alert alert-danger">
                                Usuário ou senha incorreto!<br>
                                Por favor tente novamente agora!
                            </p>
                        {% endif %}
                        <div class="form-group">
                            <div class="col-xs-12">
                                <input class="form-control" type="text" required="" name="username" placeholder="Username">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-xs-12">
                                <input class="form-control" type="password" required="" name="password" placeholder="Senha">
                            </div>
                        </div>

                        <div class="form-group text-center m-t-40">
                            <div class="col-xs-12">
                                <button class="btn btn-primary btn-block btn-lg waves-effect waves-light" type="submit">Acessar</button>
                            </div>
                        </div>

                        <div class="form-group m-t-30 m-b-0">
                            <div class="col-sm-7">
                                <a href="pages-recoverpw.html" class="text-muted"><i class="fa fa-lock m-r-5"></i> Esqueceu a senha?</a>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>



        <!-- jQuery  -->
        <script src="{% static '/js/jquery.min.js' %}"></script>
        <script src="{% static '/js/bootstrap.min.js' %}"></script>
        <script src="{% static '/js/modernizr.min.js' %}"></script>
        <script src="{% static '/js/detect.js' %}"></script>
        <script src="{% static '/js/fastclick.js' %}"></script>
        <script src="{% static '/js/jquery.slimscroll.js' %}"></script>
        <script src="{% static '/js/jquery.blockUI.js' %}"></script>
        <script src="{% static '/js/waves.js' %}"></script>
        <script src="{% static '/js/wow.min.js' %}"></script>
        <script src="{% static '/js/jquery.nicescroll.js' %}"></script>
        <script src="{% static '/js/jquery.scrollTo.min.js' %}"></script>

        <script src="{% static '/js/app.js' %}"></script>

    </body>
</html>