estudante/api/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'api'

urlpatterns = [
    path('', login_required(views.index), name="inicio"),
    path('acessar/', views.loginView, name="acessar"),
    path('sair/', login_required(views.logoutView), name="sair"),
    path('criando/', views.cadastrarEstudante, name="criando"),
    path('gerarCSRF/', views.gerarCSRF, name="gerarCSRF"),
    path('buscarEstudante/', views.buscarEstudante, name="buscarEstudante"),
    path('removerEstudante/', views.removerEstudante, name="removerEstudante"),
    path('verificaEstudante/', views.verfificaEstudante, name="verificandoEstudante"),
    path('listandoHistorico/', login_required(views.listarHistorico), name="listandoHistorico"),
    path('buscarLivro/', login_required(views.buscarLivro), name="buscandoHistorico")
]

estudante/estudante/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('api/', include('api.urls')),
    path('', RedirectView.as_view(url='api/')),
]

estudante/api/models.py
from django.db import models
from django.contrib.auth.models import User

class Estudante(User):
    matricula = models.CharField(max_length=15)

estudante/api/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.views import login, logout
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.http import JsonResponse, HttpResponse
from django.middleware.csrf import get_token
from django.views.decorators.csrf import csrf_exempt
from .serialization import *
import requests, json
from django.template.loader import render_to_string

IP_livro = "http://nginx/livro"

def index(request):
    if request.method == "GET":
        usuario = Estudante.objects.get(id = request.user.id)
        return render(request, 'index.html', {'matricula': usuario.matricula})

def loginView(request, *args, **kwargs):

    if request.user.is_authenticated:
        return redirect('api:inicio')

    kwargs['extra_context'] = {'next': reverse('api:acessar')}
    kwargs['template_name'] = 'login.html'
    return login(request, *args, **kwargs)

def logoutView(request, *args, **kwargs):
    kwargs['next_page'] = reverse('api:acessar')
    return logout(request, *args, **kwargs)

@api_view(['GET', 'POST'])
def cadastrarEstudante(request):
    if request.method == 'POST':
        if request.POST['senha'] == request.POST['repetirSenha']:
            if Estudante.objects.all().filter(matricula=request.POST['matricula']).count() == 0:
                if Estudante.objects.all().filter(email=request.POST['email']).count() == 0:
                    if Estudante.objects.all().filter(username=request.POST['username']).count() == 0:
                        user = Estudante()
                        user.email = request.POST['email']
                        user.username = request.POST['username']
                        user.first_name = request.POST['primeiroNome']
                        user.last_name = request.POST['ultimoNome']
                        user.set_password(request.POST['senha'])
                        user.matricula = request.POST['matricula']
                        user.save()
                        return Response({'status': 'success', 'mensagem': 'Usuário cadastrado com sucesso!'})
                    else:
                        return Response({'status': 'danger', 'mensagem': 'Username já está cadastrado'})
                else:
                    return Response({'status': 'danger', 'mensagem': 'Email já cadastrado no sistema'})
            else:
                return Response({'status': 'danger', 'mensagem': 'Matrícula já cadastrada no sistema'})
        else:
            return Response({'status':'danger', 'mensagem':'Senhas não combinam'})
    else:
        return HttpResponse("Nada")

@api_view(['GET'])
def gerarCSRF(request):
    if request.method == 'GET':
        return JsonResponse({'csrf': get_token(request)})


@csrf_exempt
def buscarEstudante(request):
    if request.method == 'GET':
        return HttpResponse('Estudante')
    elif request.method == 'POST':
        matricula = request.POST.get('matricula')
        if matricula is not None:
            normal = Estudante.objects.filter(matricula__contains=matricula)
            if normal:
                serializado = EstudanteSerializer(normal, many=True)
                return JsonResponse({'dados': serializado.data})
            else:
                return JsonResponse({'dados': -1})

@api_view(['POST'])
@csrf_exempt
def removerEstudante(request):
    matricula = request.POST['matricula']
    Estudante.objects.get(matricula=matricula).delete()
    return Response({'deletado':True})

@api_view(['POST'])
@csrf_exempt
def verfificaEstudante(request):
    matricula = request.POST['matricula']
    estudante = Estudante.objects.filter(matricula=matricula)
    if estudante:
        return Response({'status': 1, 'dados': EstudanteSerializer(estudante, many=True).data})
    else:
        return Response({'status': -1})

def listarHistorico(request):
    if request.method == 'POST':
        matricula = request.POST['matricula']
        estudante = Estudante.objects.filter(matricula=matricula)
        nomeEstudante = estudante[0].first_name + ' ' + estudante[0].last_name
        historico = requests.post(IP_livro + '/api/historicoEmprestimos/', data={'matricula': matricula})
        if historico.json()['status'] == 1:
            templateHistorico = render_to_string('alugados.html', {'livros': historico.json()['conteudo']})
            return JsonResponse({'nomeEstudante': nomeEstudante, 'conteudo': templateHistorico})
        else:
            return JsonResponse({'nomeEstudante': nomeEstudante, 'conteudo': "Não há nada nos registros"})

def buscarLivro(request):
    if request.method == 'POST':
        codigo = request.POST['codigo']
        lista = requests.post(IP_livro + '/api/buscarLivroNome/', data={'codigo': codigo})
        if lista.json()['dados'] != -1:
            template = render_to_string('livros/resultadoPesquisaLivro.html', {'livros': lista.json()['dados']})
            return JsonResponse({'retorno': template})
        else:
            return JsonResponse({'retorno': 'Não foi possível encontrar'})

estudante/api/templates/alugados.html
<table class="table table-striped">
    <thead>
        <tr>
            <th>Título</th>
            <th>Código</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
{% for livro in livros %}
    {% if livro.status == 0 %}
        <tr>
            <td>{{livro.titulo}}</td>
            <td>{{livro.codigo}}</td>
            <td>Entregue</td>
        </tr>
    {% else %}
        <tr>
            <td>{{livro.titulo}}</td>
            <td>{{livro.codigo}}</td>
            <td>Ainda não entregue</td>
        </tr>
    {% endif %}
{% endfor %}
    </tbody>
</table>

estudante/api/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8" />
        <title>Estudantes - {% block titulo %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta content="Admin Dashboard" name="description" />
        <meta content="ThemeDesign" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/icons.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">

    </head>


    <body class="fixed-left layout2">

        <!-- Begin page -->
        <div id="wrapper">

            <!-- Top Bar Start -->
            <div class="topbar">
                <!-- LOGO -->
                <div class="topbar-left">
                    <div class="text-center">
                        <a href="{% url 'api:inicio' %}" class="logo">Estudante <span>UFPI</span></a>
                        <a href="{% url 'api:inicio' %}" class="logo-sm"><span>E</span></a>
                        <!--<a href="index.html" class="logo"><img src="{% static 'images/logo_white_2.png" height="28"></a>-->
                        <!--<a href="index.html" class="logo-sm"><img src="{% static 'images/logo_sm.png" height="36"></a>-->
                    </div>
                </div>
                <!-- Button mobile view to collapse sidebar menu -->
                <div class="navbar navbar-default" role="navigation">
                    <div class="container">
                        <div class="">
                            <div class="pull-left">
                                <button type="button" class="button-menu-mobile open-left waves-effect waves-light">
                                    <i class="ion-navicon"></i>
                                </button>
                                <span class="clearfix"></span>
                            </div>

                            <ul class="nav navbar-nav navbar-right pull-right">
                                <li class="dropdown">
                                    <a href="" class="dropdown-toggle profile waves-effect waves-light" data-toggle="dropdown" aria-expanded="true">
                                                <span class="profile-username">
                                                    {{request.user.first_name}} {{request.user.last_name}}<br/>
                                                    <small>Estudante</small>
                                                </span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="{% url 'api:sair' %}"> Sair</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <!--/.nav-collapse -->
                    </div>
                </div>
            </div>
            <!-- Top Bar End -->


            <!-- ========== Left Sidebar Start ========== -->

            <div class="left side-menu">
                <div class="sidebar-inner slimscrollleft">

                    <div class="user-details">
                        <div class="user-info">
                            <div class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">{{request.user.first_name}} {{request.user.last_name}}</a>
                            </div>

                            <p class="text-muted m-0">Estudante</p>
                        </div>
                    </div>
                    <!--- Divider -->


                    <div id="sidebar-menu">
                        <ul>
                            <li>
                                <a href="{% url 'api:inicio' %}" class="waves-effect"><i class="mdi mdi-home"></i><span> Painel Inicial</span></a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div> <!-- end sidebarinner -->
            </div>
            <!-- Left Sidebar End -->

            <!-- Start right Content here -->

            <div class="content-page">
                <!-- Start content -->
                <div class="content">

                    {% block content %}{% endblock %}

                </div> <!-- content -->

                <footer class="footer">
                    © 2019 UFPI - Todos os direitos reservados.
                </footer>

            </div>
            <!-- End Right content here -->

        </div>
        <!-- END wrapper -->


        <!-- jQuery  -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/modernizr.min.js' %}"></script>
        <script src="{% static 'js/detect.js' %}"></script>
        <script src="{% static 'js/fastclick.js' %}"></script>
        <script src="{% static 'js/jquery.slimscroll.js' %}"></script>
        <script src="{% static 'js/jquery.blockUI.js' %}"></script>
        <script src="{% static 'js/waves.js' %}"></script>
        <script src="{% static 'js/wow.min.js' %}"></script>
        <script src="{% static 'js/jquery.nicescroll.js' %}"></script>
        <script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>

        <script src="{% static 'js/app.js' %}"></script>

        <script src="{% static 'js/formulariosEstudante.js' %}"></script>

    </body>
</html>

estudante/api/templates/index.html
{% extends "base.html" %}
{% block titulo %}Início{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2">
        <input type="hidden" name="urlHistorico" value="{%url 'api:listandoHistorico'%}">
        {% csrf_token %}
    </div>
    <div class="col-md-4">
        <div class="panel">
            <div class="panel-body text-center">
                <h2>Livros</h2>
            </div>
        </div>
        <div class="list-group">
            <a href="" class="list-group-item" data-toggle="modal" data-target="#pesquisar">Pesquisar</a>
        </div> <!-- list-group -->
    </div>
    <div class="col-md-4">
        <div class="panel">
            <div class="panel-body text-center">
                <h2>Meus Emprestimos</h2>
            </div>
        </div>
        <div class="list-group">
            <a href="" class="list-group-item" onclick="listarHistoricoEstudante('{{matricula}}')" data-toggle="modal" data-target="#myModal">Histórico</a>
        </div> <!-- list-group -->
    </div>
    <div class="col-md-2">
    </div>
</div>
<!-- sample modal content -->
<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">Estudante: <span class="text-primary" id="NomeEstudanteModal"></span></h4>
            </div>
            <div class="modal-body">
                <div id="resultadoModal"></div>
                <div id="listaHistorico"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Fechar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- modal pesquisa -->
<div id="pesquisar" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="pesquisarLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="myModalLabel">Pesquisar</h4>
                </div>
                <div class="modal-body">
                    <div class="container-fluid">
                        <div class="col-md-4">
                            <input type="text" name="pesquisar" class="form-control" onkeyup="buscarLivro(this.value)" placeholder="Nome do livro">
                            <input type="hidden" name="urlPesquisar" value="{% url 'api:buscandoHistorico' %}">
                        </div>
                        <div class="col-md-8" id="resultado"></div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Fechar</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal pesquisa -->
{% endblock %}

estudante/api/templates/livros/listar/alugados.html
<table class="table table-striped">
    <thead>
        <tr>
            <th>Título</th>
            <th>Código</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
{% for livro in livros %}
    {% if livro.status == 0 %}
        <tr>
            <td>{{livro.titulo}}</td>
            <td>{{livro.codigo}}</td>
            <td>Entregue</td>
        </tr>
    {% else %}
        <tr>
            <td>{{livro.titulo}}</td>
            <td>{{livro.codigo}}</td>
            <td><input type="button" class="btn btn-success" onclick="confirmarEntregaEmprestimo('{{livro.id}}')" value="Confirmar Entrega"></td>
        </tr>
    {% endif %}
{% endfor %}
    </tbody>
</table>

estudante/api/templates/livros/listar/estudante.html
{% for estudante in estudantes %}
<div class="col-md-12">
    <div class="panel">
        <div class="panel-body">
            <b>Nome:</b> {{estudante.first_name}} {{estudante.last_name}} <b style="margin-left:10px;">Matrícula: </b>{{estudante.matricula}} <b style="margin-left:10px;">Email: </b>{{estudante.email}} 
            <button type="button" class="btn btn-primary waves-effect waves-light" data-toggle="modal" data-target="#myModal" style="float:right" onclick="listarHistoricoEstudante('{{estudante.matricula}}')">Histórico de emprestimos</button>
        </div>
    </div>
</div>
{% endfor %}

<!-- sample modal content -->
<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="myModalLabel">Estudante: <span class="text-primary" id="NomeEstudanteModal"></span></h4>
                </div>
                <div class="modal-body">
                    <div id="resultadoModal"></div>
                    <div id="listaHistorico"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Fechar</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    

estudante/api/templates/livros/listar/pesquisa.html
{% for livro in livros %}
<div class="col-md-12">
    <div class="panel">
        <div class="panel-body">
                <b>Título:</b> {{livro.titulo}}
                <b>Autor:</b> {{livro.autor}}
                <b>Volume:</b> {{livro.volume}}
                <b>Versão:</b> {{livro.versao}}
                <b>Código:</b> {{livro.codigo}}
            <button class="btn btn-primary" style="float:right" onclick="removerLivro('{{livro.codigo}}')">Remover</button><button class="btn btn-success" style="float:right; margin-right: 10px;">Histórico de emprestimos</button>
        </div>
    </div>
</div>
{% endfor %}
    

estudante/api/templates/livros/listar/pesquisaEmprestar.html
{% for livro in livros %}
<div class="col-md-12">
    <div class="panel">
        <div class="panel-body">
                <b>Título:</b> {{livro.titulo}}
                <b>Autor:</b> {{livro.autor}}
                <b>Volume:</b> {{livro.volume}}
                <b>Versão:</b> {{livro.versao}}
                <b>Código:</b> {{livro.codigo}}
            <button class="btn btn-primary" style="float:right" onclick="emprestandoLivro('{{livro.codigo}}')">Emprestar</button>
        </div>
    </div>
</div>
{% endfor %}
    

estudante/api/templates/livros/resultadoPesquisaLivro.html
{% for livro in livros %}
<div class="panel">
    <div class="panel-body badge-dark text-white">
        <b>Título:</b> {{livro.titulo}}
        <b>Autor:</b> {{livro.autor}}
        <b>Volume:</b> {{livro.volume}}
        <b>Versão:</b> {{livro.versao}}
        <b>Código:</b> {{livro.codigo}}
    </div>
</div>
{% endfor %}
    

estudante/api/templates/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8" />
        <title>Estudante - Login</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta content="Admin Dashboard" name="description" />
        <meta content="ThemeDesign" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />


        <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static '/css/icons.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static '/css/style.css' %}" rel="stylesheet" type="text/css">

    </head>


    <body>

        <!-- Begin page -->
        <div class="accountbg"><div class="accountbgOverlay"></div></div>
        <div class="wrapper-page">
            <div class="panel panel-color panel-primary panel-pages">

                <div class="panel-body painelConta">
                    <h3 class="text-center m-t-0 m-b-15">
                        <a href="#" class=" logo-admin"><span>Estudante</span></a>
                        <small><span class="label label-default">UFPI</span></small>
                    </h3>
                    <hr>
                    <h4 class="text-muted text-center m-t-0"><b>Acesso</b></h4>

                    <form class="form-horizontal m-t-20" method="POST">
                        {% csrf_token %}
                        {% if form.errors %}
                            <p class="alert alert-danger">
                                Usuário ou senha incorreto!<br>
                                Por favor tente novamente agora!
                            </p>
                        {% endif %}
                        <div class="form-group">
                            <div class="col-xs-12">
                                <input class="form-control" type="text" required="" name="username" placeholder="Username">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-xs-12">
                                <input class="form-control" type="password" required="" name="password" placeholder="Senha">
                            </div>
                        </div>

                        <div class="form-group text-center m-t-40">
                            <div class="col-xs-12">
                                <button class="btn btn-primary btn-block btn-lg waves-effect waves-light" type="submit">Acessar</button>
                            </div>
                        </div>

                        <div class="form-group m-t-30 m-b-0">
                            <div class="col-sm-7">
                                <a href="pages-recoverpw.html" class="text-muted"><i class="fa fa-lock m-r-5"></i> Esqueceu a senha?</a>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>



        <!-- jQuery  -->
        <script src="{% static '/js/jquery.min.js' %}"></script>
        <script src="{% static '/js/bootstrap.min.js' %}"></script>
        <script src="{% static '/js/modernizr.min.js' %}"></script>
        <script src="{% static '/js/detect.js' %}"></script>
        <script src="{% static '/js/fastclick.js' %}"></script>
        <script src="{% static '/js/jquery.slimscroll.js' %}"></script>
        <script src="{% static '/js/jquery.blockUI.js' %}"></script>
        <script src="{% static '/js/waves.js' %}"></script>
        <script src="{% static '/js/wow.min.js' %}"></script>
        <script src="{% static '/js/jquery.nicescroll.js' %}"></script>
        <script src="{% static '/js/jquery.scrollTo.min.js' %}"></script>

        <script src="{% static '/js/app.js' %}"></script>

    </body>
</html>