bibliotecario/api/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'api'

urlpatterns = [
    path('', login_required(views.index), name="inicio"),
    path('acessar/', views.loginView, name='acessar'),
    path('sair/', login_required(views.logoutView), name='sair'),

    path('cadastrar/estudante/', login_required(views.cadastrarEstudante), name="cadastrarEstudante"),
    path('pesquisar/estudante/', login_required(views.pesquisarEstudante), name="pesquisarEstudante"),
    path('remover/estudante/', login_required(views.removerEstudante), name="removerEstudante"),

    path('emprestar/livro/', login_required(views.emprestarLivro), name="emprestarLivro"),
    path('emprestandoLivro', login_required(views.emprestandoLivro), name="emprestandoLivro"),
    path('emprestar/livro/realizar/', login_required(views.finalizarEmprestimo), name="emprestandoLivroFinalizar"),
    path('cadastrar/livro/', login_required(views.cadastrarLivro), name="cadastrarLivro"),
    path('receber/livro/', login_required(views.receberLivro), name="receberLivro"),
    path('remover/livro/', login_required(views.removerLivro), name="removerLivro"),
    path('removendoLivro/', login_required(views.removendoLivro), name="removendoLivro"),
    path('listarHistorico', login_required(views.listarHistorico), name="listarHistorico"),
    path('confirmandoEntregaEmprestimo/', login_required(views.confirmandoEntregaEmprestimo), name='confirmandoEntrega'),

]

bibliotecario/bibliotecario/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('api.urls', namespace='api')),
]

bibliotecario/api/models.py
from django.db import models

# Create your models here.

class recuperarSenha(models.Model):
    token = models.CharField(max_length=256)
    emailUser = models.CharField(max_length=40)

bibliotecario/api/forms.py
from django import forms
from django.db import models

class FormularioLogin(forms.Form):
    username = forms.CharField(required=True, label='',
                               widget=forms.TextInput(attrs={'placeholder': 'Usuário', 'class': 'form-control'}))
    password = forms.CharField(required=True, label='',
                               widget=forms.PasswordInput(attrs={'placeholder': 'Senha', 'class': 'form-control'}))

bibliotecario/api/views.py
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.contrib.auth.views import login, logout
from django.http import JsonResponse
import requests, json

IP_estudante = 'http://nginx/estudante'
IP_livro = 'http://nginx/livro'

# Create your views here.
def index(request):
    return render(request, 'index.html')

def loginView(request, *args, **kwargs):

    if request.user.is_authenticated:
        return redirect('api:inicio')

    kwargs['extra_context'] = {'next': reverse('api:acessar')}
    kwargs['template_name'] = 'login.html'
    return login(request, *args, **kwargs)

def logoutView(request, *args, **kwargs):
    kwargs['next_page'] = reverse('api:acessar')
    return logout(request, *args, **kwargs)

'''
    Estudantes
'''

def cadastrarEstudante(request):
    if request.GET is not None:
        return render(request, 'estudante/cadastrar.html')

def pesquisarEstudante(request):
    if request.method == 'GET':
        return render(request, 'estudante/pesquisar.html')
    elif request.method == 'POST':
        matricula = request.POST['matricula']
        session = requests.Session()
        session.trust_env = False
        lista = requests.post(IP_estudante+'/api/buscarEstudante/', data={'matricula': matricula})
        if lista.json()['dados'] != -1:
            template = render_to_string('estudante/listar/pesquisa.html', {'estudantes': lista.json()['dados']})
            return JsonResponse({'retorno': template})
        else:
            return JsonResponse({'retorno': 'Não foi possível encontrar'})

def removerEstudante(request):
    if request.method == 'POST':
        matricula = request.POST['matricula']
        lista = requests.post(IP_estudante + '/api/removerEstudante/', data={'matricula': matricula})
        if lista.json()['deletado']:
            return JsonResponse({'status':'success', 'mensagem':'Estudante removido com sucesso'})
        else:
            return JsonResponse({'status': 'danger', 'mensagem': 'Erro ao remover estudante'})

'''
    Livros
'''

def emprestarLivro(request):
    if request.method == 'GET':
        return render(request, 'livros/emprestar.html')
    elif request.method == 'POST':
        codigo = request.POST['codigo']
        lista = requests.post(IP_livro + '/api/buscarLivroNome/', data={'codigo': codigo})
        if lista.json()['dados'] != -1:
            template = render_to_string('livros/listar/pesquisaEmprestar.html', {'livros': lista.json()['dados']})
            return JsonResponse({'retorno': template})
        else:
            return JsonResponse({'retorno': 'Não foi possível encontrar'})

def emprestandoLivro(request):
    if request.method == 'POST':
        codigo = request.POST['codigo']
        return JsonResponse({'retorno': render_to_string('livros/emprestando.html', {'codigo': codigo})})

def finalizarEmprestimo(request):
    if request.method == 'POST':
        codigo = request.POST['codigo']
        matricula = request.POST['matriculaT']
        if matricula != "":
            verificarEstudante = requests.post(IP_estudante + '/api/verificaEstudante/', data={'matricula': matricula})
            if verificarEstudante.json()['status'] == 1:
                lista = requests.post(IP_livro + '/api/emprestarLivro/', data={'codigo': codigo, 'matricula': matricula})
                if lista.json()['status'] == 1:
                    return JsonResponse({'status': 'success', 'mensagem': 'Livro emprestado com sucesso!'})
            else:
                return JsonResponse({'status': 'danger', 'mensagem': 'Estudante Não Existe'})
        else:
            return JsonResponse({'status': 'danger', 'mensagem': 'Preencha todos os campos!'})


def receberLivro(request):
    if request.method == 'GET':
        return render(request, 'livros/receber.html')
    elif request.method == 'POST':
        matricula = request.POST['matricula']
        lista = requests.post(IP_estudante + '/api/buscarEstudante/', data={'matricula': matricula})
        if lista.json()['dados'] != -1:
            template = render_to_string('livros/listar/estudante.html', {'estudantes': lista.json()['dados']})
            return JsonResponse({'retorno': template})
        else:
            return JsonResponse({'retorno': 'Não foi possível encontrar'})

def cadastrarLivro(request):
    return render(request, 'livros/cadastrar.html')

def removerLivro(request):
    if request.method == 'GET':
        return render(request, 'livros/remover.html')
    elif request.method == 'POST':
        codigo = request.POST['codigo']
        lista = requests.post(IP_livro + '/api/buscarLivro/', data={'codigo': codigo})
        if lista.json()['dados'] != -1:
            template = render_to_string('livros/listar/pesquisa.html', {'livros': lista.json()['dados']})
            return JsonResponse({'retorno': template})
        else:
            return JsonResponse({'retorno': 'Não foi possível encontrar'})

def removendoLivro(request):
    if request.method == 'POST':
        codigo = request.POST['codigo']
        lista = requests.post(IP_livro + '/api/removerLivro/', data={'codigo': codigo})
        if lista.json()['deletado']:
            return JsonResponse({'status':'success', 'mensagem':'Livro removido com sucesso'})
        else:
            return JsonResponse({'status': 'danger', 'mensagem': 'Erro ao remover livro'})

def listarHistorico(request):
    if request.method == 'POST':
        matricula = request.POST['matricula']
        Estudante = requests.post(IP_estudante+'/api/buscarEstudante/', data={'matricula': matricula})
        dados = Estudante.json()['dados'][0]
        nomeEstudante = dados['first_name'] + ' ' + dados['last_name']
        historico = requests.post(IP_livro + '/api/historicoEmprestimos/', data={'matricula': matricula})
        if historico.json()['status'] == 1:
            templateHistorico = render_to_string('livros/listar/alugados.html', {'livros': historico.json()['conteudo']})
            return JsonResponse({'nomeEstudante': nomeEstudante, 'conteudo': templateHistorico})
        else:
            return JsonResponse({'nomeEstudante': nomeEstudante, 'conteudo': "Não há nada nos registros"})

def confirmandoEntregaEmprestimo(request):
    if request.method == 'POST':
        idEmprestimo = request.POST['idEmprestimo']
        confirmando = requests.post(IP_livro + '/api/confirmandoRecebimentoEmprestimo/', data={'idEmprestimo': idEmprestimo})
        print(confirmando)
        if confirmando.json()['status'] == 1:
            return JsonResponse({'status': 'success', 'mensagem': 'Confirmação realizada com sucesso!'})
        else:
            return JsonResponse({'status': 'danger', 'mensagem': 'Erro na confirmação da entrega, tente novamente!'})

bibliotecario/api/templates/livros/cadastrar.html
{% extends "base.html" %}
{% block titulo %}Cadastrar Livro{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h3>Cadastrar Livro</h3>
        <div class="panel">
            <div class="panel-body">
                <div class="container">
                    <div class="row">
                        <div id="resultado"></div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" name="titulo" id="titulo" class="form-control" placeholder="Titulo">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" name="autor" id="autor" class="form-control" placeholder="Autor">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <input type="text" name="volume" id="volume" class="form-control" placeholder="Volume">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <input type="text" name="versao" id="versao" class="form-control" placeholder="Versão">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <input type="text" name="codigo" id="codigo" class="form-control" placeholder="Código">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-success btn-block btn-lg" onclick="cadastrarLivro()">Cadastrar</button>
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

bibliotecario/api/templates/livros/emprestando.html
<div class="container">
    <div class="panel">
        <div class="panel-body">
            <div class="row">
                <small>Livro Selecionado:</small> <span><b>TTESTE</b></span>
            </div>
            <div class="row form-group" style="margin-top:10px;">
                <div class="col-md-6 form-group">
                    <input type="text" class="form-control" value="{{codigo}}" name="codigoCampo" id="codigoCampo" disabled>
                </div>
                <div class="col-md-6 form-group">
                    <input type="text" class="form-control" id="matriculaCampo" id="matriculaCampo" placeholder="Matrícula do Estudante">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-12">
                    <input type="button" class="btn btn-success btn-lg btn-block" onclick="finalizarEmprestimoLivro()" value="Emprestar">
                </div>
            </div>
        </div>
    </div>
</div>

bibliotecario/api/templates/livros/emprestar.html
{% extends "base.html" %}
{% block titulo %}Emprestar Livro{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-3">
        <h4>Emprestar</h4>
        <input type="text" name="pesquisar" class="form-control" onkeyup="buscarLivro(this.value)" placeholder="Nome do livro">
        {% csrf_token %}
        <input type="hidden" name="urlEmprestando" value="{% url 'api:emprestandoLivro' %}">
        <input type="hidden" name="urlFinalizandoEmprestimo" value="{% url 'api:emprestandoLivroFinalizar' %}">
    </div>
    <div class="col-md-9">
        <div id="retorno"></div>
        <div id="resultado"></div>
    </div>
</div>
{% endblock %}

bibliotecario/api/templates/livros/receber.html
{% extends "base.html" %}
{% block titulo %}Receber Livro{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-3">
        <input type="text" name="pesquisar" class="form-control" placeholder="Matrícula do estudante" onkeyup="buscarEstudanteReceber(this.value)">
        {% csrf_token %}
        <input type="hidden" name="urlHistorico" value="{% url 'api:listarHistorico' %}">
        <input type="hidden" name="urlPesquisar" value="{% url 'api:pesquisarEstudante' %}">
        <input type="hidden" name="urlConfirmaEntrega" value="{% url 'api:confirmandoEntrega' %}">
    </div>
    <div class="col-md-9" >
        <div id="retorno"></div>
        <div id="resultado"></div>
    </div>
</div>
{% endblock %}

bibliotecario/api/templates/livros/remover.html
{% extends "base.html" %}
{% block titulo %}Remover Livro{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-3">
        <input type="text" name="pesquisar" class="form-control" onkeyup="buscarLivro(this.value)" placeholder="Código do livro">
        {% csrf_token %}
        <input type="hidden" name="urlRemover" value="{% url 'api:removendoLivro' %}">
    </div>
    <div class="col-md-9" id="retorno">
        <div id="retorno"></div>
        <div id="resultado"></div>
    </div>
</div>
{% endblock %}